### ISSUE TITLE
Unable to continue

### ISSUE THREAD

**Issue by CoderJoeW** [flaminggenius/CSVAnalyzerPro#31]
Currently I feel lost on github with all the pull request and merges and conflicts I'm just not familiar with any of it and with the current project state I feel I am unable to continue working with the github repo but will still make sure the code is somewhere online

**I am looking for a maintainer** I do like the use of github and i want to continue working with it

If someone is willing to be a maintaner then the project will live on in github :)

**Comment by fly-man-** [comment]
Goodevening,

Do you have a working version that compiles at the moment ? Because I would rather reset the whole "master" branch to a clean version that compiles and then reapply patches to find out where things go broken.

And I think you just need a better tool that can take away the issues you might have with Github so you can program this great program without the need of having to upload the files manually.

If you are still looking for a maintainer, please let me know

**Comment by CoderJoeW** [comment]
Hey fly-man if your interested in being a maintainer I would 100% love to revive this project

**Comment by sergeevabc** [comment]
Windows binary is missing.
